homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow
  # Customizations
  customize: 
  # Load integrations
  packages: !include_dir_named integrations

# Enable the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enable configuration UI
config:

# Serve your HA on the Internet
http:
  base_url: !secret base_url 

# Check for available updates
updater:

# Discover and configure some devices automatically
discovery:
  ignore:
    - igd

# Enable support for tracking state changes over time
history:
  exclude:
    domains:
      - automation
      - script
      - device_tracker

# Fancy graphs in History panel
history_graph:

# View all events in a logbook
logbook:
  exclude:
     entities:
       - binary_sensor.bedroom_motion
       - binary_sensor.camera_motion

# Limit database usage
recorder:
  purge_keep_days: 5
  purge_interval: 2
  #db_url: sqlite:////home/pi/hass/home-assistant_v2.db
 
# Enable a map showing the location of tracked devices
map:

# Enable notifications
notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_chat_id

# Default groups
group: 

# API for diagnostics
system_health:

# =========== Entities ============
sensor: !include_dir_list entities/sensors
binary_sensor: !include_dir_list entities/binary_sensors
switch: !include_dir_list entities/switches
light: !include_dir_list entities/lights
tts: !include_dir_list entities/tts
media_player: !include_dir_list entities/media_players
camera: !include_dir_list entities/cameras
device_tracker: !include_dir_list entities/device_trackers
person: !include_dir_list entities/persons
zone: !include_dir_list entities/zones

# ========== Automations ==========
automation: !include_dir_merge_list automations
script: !include_dir_merge_list scripts