alias: Notify DEVICE state
hide_entity: false
trigger:
- entity_id: device_tracker.oneplus_5t,device_tracker.94_65_2d_46_f8_44
  platform: state
condition:
- after: 08:00:00
  before: '23:00:00'
  condition: time
action:
- data_template:
    message: _{{ trigger.from_state.name }}_ is now *{{ trigger.to_state.state |
      upper }}*
    title: 📲
  service: notify.telegram