alias: Christmas tree
sequence:
- data:
    entity_id: media_player.bedroom_speaker
    media_content_id: /local/vlesu.mp3
    media_content_type: audio/mp3
  service: media_player.play_media
- alias: ''
  data:
    entity_id: switch.tv_switch
  service: switch.turn_on
